### ISSUE TITLE
IOU value 0

### ISSUE THREAD

**Issue by MelanieFo94** [ayoolaolafenwa/PixelLib#107]
Hi,
I tested the Custom Training with 7 Lines of Code program. I have a dataset with train and test folder as required. The train.json and test.json were generated without any problem. 

I train with a custom dataset, just one class. I have adapted all the code following this github and this "tutorial" : https://towardsdatascience.com/custom-instance-segmentation-training-with-7-lines-of-code-ff340851e99b

I set 50 epochs to train with my custom dataset.

But when I evaluated my models, the IOU value was 0 for all my models.

Do you have any explanation ? Apparently i'm not the only one to have this problem.

**Comment by aminrabinia** [comment]
> Hi, I tested the Custom Training with 7 Lines of Code program. I have a dataset with train and test folder as required. The train.json and test.json were generated without any problem.
> 
> I train with a custom dataset, just one class. I have adapted all the code following this github and this "tutorial" : https://towardsdatascience.com/custom-instance-segmentation-training-with-7-lines-of-code-ff340851e99b
> 
> I set 50 epochs to train with my custom dataset.
> 
> But when I evaluated my models, the IOU value was 0 for all my models.
> 
> Do you have any explanation ? Apparently i'm not the only one to have this problem.

I had the same problem and I think it resolved when I converted my images from png to jpg.
