### ISSUE TITLE
how can I obtain the labels for the pixels?

### ISSUE THREAD

**Issue by shashi-netra** [ayoolaolafenwa/PixelLib#11]
Is that pixel color code <> label output somewhere? For example, can the bounding boxes be exported into a json dictionary?

**Comment by ayoolaolafenwa** [comment]
Presently you cannot export the anchors of the bounding boxes into a single json file. 
But you can obtain the following arrays.
-Detected Objects' arrays

-Objects' corresponding class_ids' arrays

-Segmentation masks' arrays

-Output's array

By using this code

  `segmask, output = segment_image.segmentImage()`

You can test the code for obtaining arrays and print out the shape of the output by modifying the instance segmentation code below.
  `import pixellib
  from pixellib.instance import instance_segmentation
  import cv2

  instance_seg = instance_segmentation()
  instance_seg.load_model("mask_rcnn_coco.h5")
  segmask, output = instance_seg.segmentImage("sample2.jpg")
  cv2.imwrite("img.jpg", output)
  print(output.shape)`
Obtain arrays of segmentation with bounding boxes by including the parameter show_bboxes.

  `segmask, output = segment_image.segmentImage(show_bboxes = True)`
Full code
 ` import pixellib
  from pixellib.instance import instance_segmentation
  import cv2

  instance_seg = instance_segmentation()
  instance_seg.load_model("mask_rcnn_coco.h5")
  segmask, output = instance_seg.segmentImage("sample2.jpg", show_bboxes= True)
  cv2.imwrite("img.jpg", output)
  print(output.shape)`
