### ISSUE TITLE
unable load model in docker container. it shows no error nor loading..

### ISSUE THREAD

**Issue by ishanShahzad** [ayoolaolafenwa/PixelLib#12]
when i use it with gpu in docker container it shows:
`E tensorflow/stream_executor/cuda/cuda_driver.cc:1244] could not retrieve CUDA device count: CUDA_ERROR_NOT_INITIALIZED: initialization error`

when i run it without GPU it hang on load model line:
`segment_video.load_ade20k_model("deeplabv3_xception65_ade20k.h5")`

**Comment by ayoolaolafenwa** [comment]
Presently PixelLib does not support docker containers,  by the way PixelIb works fine on CPU, it will only be slower compared to GPU.  I will like to know the tensorflow version you are using.
