### ISSUE TITLE
load_model

### ISSUE THREAD

**Issue by ruchika61** [ayoolaolafenwa/PixelLib#19]
hi 
kindly help in removing this error

runfile('E:/MCSS/PixelLib-master/demo.py', wdir='E:/MCSS/PixelLib-master')
Reloaded modules: pixellib, pixellib.instance, pixellib.mask_rcnn, pixellib.utils, pixellib.config
Traceback (most recent call last):

  File "<ipython-input-5-2555d729717f>", line 1, in <module>
    runfile('E:/MCSS/PixelLib-master/demo.py', wdir='E:/MCSS/PixelLib-master')

  File "C:\Users\dell\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "C:\Users\dell\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/MCSS/PixelLib-master/demo.py", line 14, in <module>
    segment_image.load_model('mask_rcnn_coco.h5')

  File "E:\MCSS\PixelLib-master\pixellib\instance.py", line 25, in load_model
    self.model.load_weights(model_path, by_name= True)

  File "E:\MCSS\PixelLib-master\pixellib\mask_rcnn.py", line 2089, in load_weights
    from tensorflow.python.keras.saving import hdf5_format

ModuleNotFoundError: No module named 'tensorflow.python.keras.saving'

**Comment by ayoolaolafenwa** [comment]
> hi
> kindly help in removing this error
> 
> runfile('E:/MCSS/PixelLib-master/demo.py', wdir='E:/MCSS/PixelLib-master')
> Reloaded modules: pixellib, pixellib.instance, pixellib.mask_rcnn, pixellib.utils, pixellib.config
> Traceback (most recent call last):
> 
> File "", line 1, in
> runfile('E:/MCSS/PixelLib-master/demo.py', wdir='E:/MCSS/PixelLib-master')
> 
> File "C:\Users\dell\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
> execfile(filename, namespace)
> 
> File "C:\Users\dell\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
> exec(compile(f.read(), filename, 'exec'), namespace)
> 
> File "E:/MCSS/PixelLib-master/demo.py", line 14, in
> segment_image.load_model('mask_rcnn_coco.h5')
> 
> File "E:\MCSS\PixelLib-master\pixellib\instance.py", line 25, in load_model
> self.model.load_weights(model_path, by_name= True)
> 
> File "E:\MCSS\PixelLib-master\pixellib\mask_rcnn.py", line 2089, in load_weights
> from tensorflow.python.keras.saving import hdf5_format
> 
> ModuleNotFoundError: No module named 'tensorflow.python.keras.saving'

This is a tensorflow issue it has nothing to do with PixelLib. Figure it out yourself the version of tensorflow you are using if it is compatible with your software set up.
