### ISSUE TITLE
Way to train for using custom dataset

### ISSUE THREAD

**Issue by mssung94** [ayoolaolafenwa/PixelLib#2]
Hi. It seem that your model are based on COCO dataset.
Is there any way to use training my own dataset?
Thanks.

**Comment by ayoolaolafenwa** [comment]
Presently the latest version of PixelLib supports image segmentation with available pretrained models. Future versions will be upgraded to support training of custom dataset.

**Comment by dvlee1024** [comment]
@ayoolaolafenwa Waiting for future versions.

**Comment by andyqian2015** [comment]
@dvlee1024  can you run the code sucess? when I run the code 
segment_image = semantic_segmentation()
it raise the error:
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 2048, 64, 2048), (None, 256, 64, 1), (None, 256, 64, 1), (None, 256, 64, 1), (None, 256, 64, 1)]
the tensorflow version is 2.2.0
thx for your replay

**Comment by ayoolaolafenwa** [comment]
> Hi. It seem that your model are based on COCO dataset.
> Is there any way to use training my own dataset?
> Thanks.

Custom training is supported in the latest version of PixelLib.  [Read the tutorial](https://github.com/ayoolaolafenwa/PixelLib/blob/master/Tutorials/custom_train.md).
