### ISSUE TITLE
Change detection threshold for rcnn segmentation

### ISSUE THREAD

**Issue by manu12344** [ayoolaolafenwa/PixelLib#20]
How can we adjust the detection threshold while testing ? For the program below, is there someway we could input a threshold score value ?

segment_image = custom_segmentation()
segment_image.inferConfig(num_classes= 1, class_names= ["bg","vol"])
segment_image.load_model("/content/drive/My Drive/Segmentation/mask_rcnn_model.034-0.509586.h5")
segment_image.segmentImage("/content/drive/My Drive/Segmentation/tn1.jpg", show_bboxes=True, output_image_name= "/content/drive/My Drive/Segmentation/n1.jpg")

**Comment by ayoolaolafenwa** [comment]
> How can we adjust the detection threshold while testing ? For the program below, is there someway we could input a threshold score value ?
> 
> segment_image = custom_segmentation()
> segment_image.inferConfig(num_classes= 1, class_names= ["bg","vol"])
> segment_image.load_model("/content/drive/My Drive/Segmentation/mask_rcnn_model.034-0.509586.h5")
> segment_image.segmentImage("/content/drive/My Drive/Segmentation/tn1.jpg", show_bboxes=True, output_image_name= "/content/drive/My Drive/Segmentation/n1.jpg")

The feature you are requesting is not supported. I will reach back to you on it when the library is upgraded to support this feature.

**Comment by ayoolaolafenwa** [comment]
@manu12344  It is now possible to set a detection threshold for a model trained with PixelLib. 

`segment_image.inferConfig(num_classes= 1, class_names= ["bg","vol"], detection_threshold = 0.7)`

The detection threshold's value by default is **0.7**, which means  that the minimum score accepted for detection is **0.7**. 
You can change **detection_threshold** to any value to suit the application of the model you trained.
