### ISSUE TITLE
Is it possible to use resnest200 as backbone

### ISSUE THREAD

**Issue by Randheerkumar** [ayoolaolafenwa/PixelLib#21]
**I want to use resnest200 as a backbone , so is it possible to use it after changing in mask_rcnn.py file**, Since resnest200 will give better result.

**Comment by ayoolaolafenwa** [comment]
> **I want to use resnest200 as a backbone , so is it possible to use it after changing in mask_rcnn.py file**, Since resnest200 will give better result.
PixelLib supports two network backbones and they are Resnet101 and Resnet50.
