### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by andyqian2015** [ayoolaolafenwa/PixelLib#3]
when I run the code
 segment_image = semantic_segmentation()
it raise the error:
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 2048, 64, 2048), (None, 256, 64, 1), (None, 256, 64, 1), (None, 256, 64, 1), (None, 256, 64, 1)]
how can I solve the problem?
wish to get you replay soon

**Comment by ayoolaolafenwa** [comment]
Please provide the full code you wrote.

**Comment by andyqian2015** [comment]
import pixellib
from pixellib.instance import instance_segmentation
from pixellib.semantic import semantic_segmentation
segment_image = semantic_segmentation()

A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 2048, 64, 2048), (None, 256, 64, 1), (None, 256, 64, 1), (None, 256, 64, 1), (None, 256, 64, 1)]

**Comment by andyqian2015** [comment]
I have soloved the problem for adjust the sequential of channel to channels to channels_last. thx for your reply
