### ISSUE TITLE
load model have error

### ISSUE THREAD

**Issue by 1abner1** [ayoolaolafenwa/PixelLib#32]
Hello 
**experiment:**
import pixellib
from pixellib.semantic import semantic_segmentation
segment_image = semantic_segmentation()
segment_image.load_pascalvoc_model("deeplabv3_xception_tf_dim_ordering_tf_kernels.h5")
segment_image.segmentAsPascalvoc(r"C:\Users\xww\Desktop\test.jpg", output_image_name = r"D:\unity_python\ma_1.jpg")

**_### have error:_**
Unable to open file (unable to open file: name = 'deeplabv3_xception_tf_dim_ordering_tf_kernels.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

where is this weights file of   "deeplabv3_xception_tf_dim_ordering_tf_kernels.h5" ？

thank you

**Comment by ayoolaolafenwa** [comment]
@1abner1  Download the model from [here](https://github.com/ayoolaolafenwa/PixelLib/releases/download/1.1/deeplabv3_xception_tf_dim_ordering_tf_kernels.h5).
