### ISSUE TITLE
Running on GPU

### ISSUE THREAD

**Issue by mab85** [ayoolaolafenwa/PixelLib#33]
I run the semantic segmentation on CPU without any errors, but when run on GPU for the same video I got the following error "UnboundLocalError: local variable 'raw_labels' referenced before assignment." Tensorflow-gpu 2.4.0 is installed.

**Comment by ayoolaolafenwa** [comment]
@mab85 PixelLib works fine on tensorflow 2.4.0.  This error occurs when the specified video path does not exists. Ensure that you used the correct video path in the code.

**Comment by mab85** [comment]
@ayoolaolafenwa Thanks for fast reply to my question, but I have the same error "File "/home/dota/anaconda3/lib/python3.7/site-packages/pixellib/instance.py", line 248, in process_video return segmask, output
UnboundLocalError: local variable 'segmask' referenced before assignment

**Comment by mab85** [comment]
@ayoolaolafenwa Its solved. This error is due to the version of opencv
