### ISSUE TITLE
mAP is 0

### ISSUE THREAD

**Issue by DerpyMan101** [ayoolaolafenwa/PixelLib#34]
I followed the tutorial at [https://towardsdatascience.com/custom-instance-segmentation-training-with-7-lines-of-code-ff340851e99b](url)

and trained the model, but I get a score of 0 for mAP. The size of my dataset is 345 images. 

`<pre>mask_rcnn_models/mask_rcnn_model.119-0.080170.h5 evaluation using iou_threshold 0.5 is 0.000000 
</pre>`

**Comment by ayoolaolafenwa** [comment]
@DerpyMan101  This is unusual. What is the **val_loss** of the model you evaluated and share your code.
