### ISSUE TITLE
where   to download   mode of  "deeplabv3_xception65_ade20k.h5"

### ISSUE THREAD

**Issue by 1abner1** [ayoolaolafenwa/PixelLib#35]
Hello ayoolaofenwa.
                                1.where   to download   mode of  "deeplabv3_xception65_ade20k.h5"
                                2.where   to download   mode of  "mask_rcnn_coco.h5"
                              

thank you
abnerxiao

**Comment by ayoolaolafenwa** [comment]
@1abner1 Both models are available in the [release](https://github.com/ayoolaolafenwa/PixelLib/releases ) of this github repository.
