### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by ebrarsahin** [ayoolaolafenwa/PixelLib#40]
Hey thank you this repository.
https://github.com/ayoolaolafenwa/PixelLib/blob/master/Tutorials/custom_inference.md.
I want to run my custom model which is frozen_inference_graph.pb but "OSError: Unable to open file (file signature notfound) "
take this error. 
Any advice ?

**Comment by ebrarsahin** [comment]
Is the h5 extension essential?

**Comment by ayoolaolafenwa** [comment]
@ebrarsahin  You have to make use of h5 models. Could you explain further did you train your model and save it as a pb file? This is because models trained with PixelLib are saved as h5 models.
