### ISSUE TITLE
Is there a way to return a transparent background?

### ISSUE THREAD

**Issue by Keepsie** [ayoolaolafenwa/PixelLib#41]
Hello, I've been going through the docs and I see alter_bg for color_bg and image_bg and even gray_bg is there a way to return a transparent background?

Appreciate the help and I love the project. I'm new to python and this got me up in running within a few days.

**Comment by ayoolaolafenwa** [comment]
It is not supported. @Keepsie you can do this; using the function that changes the background of an image with a picture, you would use a transparent image for the background of any image.

**Comment by Keepsie** [comment]
@ayoolaolafenwa Thanks I was able to work it out.
