### ISSUE TITLE
Only show mask in instance segmentation

### ISSUE THREAD

**Issue by enting8696** [ayoolaolafenwa/PixelLib#44]
i'm new in ML, thanks provide pixellib great package.

Is it possible to keep only the mask of the instance segmentation?

The result will be the same as semantic segmentation, only black background and mask.

**Comment by ayoolaolafenwa** [comment]
@enting8696  I made it possible to extract each of the segmented objects and save it as a separate image with a black background. 
You can read the tutorial from [here](https://github.com/ayoolaolafenwa/PixelLib/blob/master/Tutorials/image_instance.md).
