### ISSUE TITLE
segmask [as in: segmask, output = instance.segmentImagecontains(....)] only contains last detected object 

### ISSUE THREAD

**Issue by mstr1** [ayoolaolafenwa/PixelLib#46]
Hi Ayoola, and thank you for creating such a great and truly useful library with Pixellib.

My issue is that when I use segmentImage() like this:
`segmask, output = instance.segmentImage(....)`
The resulting segmask['extracted_objects'] will always contain only one, the LAST, segmented object, not all of them.
Is this intended behaviour, or am I missing something here?

Thanks,
Martin

**Comment by ayoolaolafenwa** [comment]
Thank you @mstr1, I would work on it and reach back to you soon on it.

**Comment by ayoolaolafenwa** [comment]
@mstr1 It has been solved. Upgrade to the latest using 
```pip3 install pixellib --upgrade
```
sample image
![image](https://user-images.githubusercontent.com/52606857/110800667-b76f1c80-827c-11eb-988a-0363629bc393.jpg)

Test code
```python
import pixellib
from pixellib.instance import instance_segmentation

segment_image = instance_segmentation()
segment_image.load_model("mask_rcnn_coco.h5")
seg, output = segment_image.segmentImage("sample4.jpg", extract_segmented_objects=True, save_extracted_objects =True,
                                         show_bboxes=True, output_image_name= "a.jpg")
res = seg["extracted_objects"]
for a in res:
    print(a.shape)
```
ouptut
I print the shapes of the extracted objects to confirm that it returned all the objects extracted. In the picture there are three objects and it prints out the shapes of the three objects which are:
```
(238, 92, 3)
(174, 260, 3)
(117, 235, 3)
```

**Comment by mstr1** [comment]
Works perfectly, thanks a lot!

**Comment by feitgemel** [comment]
Hi,
How can I extract the labels for each object ? (like person etc ....) ?

Eran

**Comment by SaiSandeepKantareddy** [comment]
are show_bboxes parameter not working for semantic segmentation?
