### ISSUE TITLE
Deploying trained model to Tesnorflow Serving

### ISSUE THREAD

**Issue by piotrlaczkowski** [ayoolaolafenwa/PixelLib#47]
I am trying to deploy trained custom model to a TFServing contained, but when I do I end-up with this signature:

```
The given SavedModel SignatureDef contains the following input(s):
  inputs['input_anchors'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, -1, 4)
      name: serving_default_input_anchors:0
  inputs['input_image'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, -1, -1, 3)
      name: serving_default_input_image:0
  inputs['input_image_meta'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 15)
      name: serving_default_input_image_meta:0
```

this means that each time I would need to provide a kind of a pre-processing function in order to format these inputs. When I look at the code it seems quite complex to fix some configs and export them in order to build everything we need.

Do you know an easy way of deploying models trained with PixelLib to TFServe ?

It would be great if you have this `export` feature somehow?

Thnx

**Comment by ayoolaolafenwa** [comment]
@piotrlaczkowski  I would advise you to read more about tensorflow serving [documentation](https://www.tensorflow.org/tfx/serving/docker).  Alternatively you could try deploying your model on a cloud computing platform like Azure.

**Comment by piotrlaczkowski** [comment]
Hi @ayoolaolafenwa,

Thank you for your comment, but I am not interested in loading the model itself as I can already do using PixeLlib or as you have suggested, but I would like to understand how can I export a trained model with some custom signature definitions. The idea is to provide only the input image at inference as input (without all anchors and boxes etc) and put it into TFServing.

From what I can find online with some old tutorials: 

https://github.com/sthalles/deeplab_v3/blob/master/serving/deeplab_saved_model.py

it seems quite complex to me and not so compatible with the current TF version, but maybe I am wrong and you could point me in the right direction or you have some similar features already or ideas?

Thank you!
