### ISSUE TITLE
Custom Model Saving and Multiple Labeled Object same Img

### ISSUE THREAD

**Issue by DeepUlu16** [ayoolaolafenwa/PixelLib#48]
Hi! Thanks for effort; 

1. How can I save the model trained by me? 
2. How to train multiple object at the same image ? And What should directory structure  for included multiple object at same image?

**Comment by ayoolaolafenwa** [comment]
@DeepUlu16  read this [tutorial](https://github.com/ayoolaolafenwa/PixelLib/blob/master/Tutorials/custom_train.md)  on custom training using PixelLib.

**Comment by Roy-Praveen** [comment]
@ayoolaolafenwa I also had the same doubt. I have posted the same question in [#167](https://github.com/ayoolaolafenwa/PixelLib/issues/167). Could you kindly check it. 
btw, great effort. Big Fan.
