### ISSUE TITLE
Is it possible to remove classifications?

### ISSUE THREAD

**Issue by NoahCardoza** [ayoolaolafenwa/PixelLib#5]
I'm pretty new to ML and I'm looking to use this in a project. I've decided to use the `mask_rcnn_coco` model, but it has a lot of classifications that I don't really need. I was wondering if it would be possible to remove classifications? Would that speed anything up?

For instance, I only need to detect the objects in this set:`{'airplane', 'bicycle', 'boat', 'car', 'motorbus', 'bus', 'motorcycle', 'train', 'truck', 'umbrella'}`

Would it be possible to configure the model to lose the weights for all the other object classifications?

**Comment by ayoolaolafenwa** [comment]
@NoahCardoza you are talking about custom object detection. Custom object detection is presently not supported in this present version of PixelLib. It will be integrated in the future versions of PixelLib.

**Comment by NoahCardoza** [comment]
Great! Thanks for the info.

**Comment by ayoolaolafenwa** [comment]
@NoahCardoza I am happy to announce that PixelLib now makes it possible to filter unused detections and detect specific classes. It also included the feature to extract segmented objects. Upgrade to the latest version of PixelLib using 
`pip3 install pixellib --upgrade.`

Check the [tutorial](https://github.com/ayoolaolafenwa/PixelLib/blob/master/Tutorials/image_instance.md)
