### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by bappaditya-td** [ayoolaolafenwa/PixelLib#54]
ValueError: Error when checking input: expected input_image_meta to have shape (17,) but got array with shape (16,)

Getting this when trying to add few samples of insect images tagged with labelme into Nature dataset. So it is becoming 3 class problem..But working fine with 2 class case of Nature

**Comment by ayoolaolafenwa** [comment]
@bappaditya-td  This is not a 3 class problem, confirm that you change the number of classes in the model configuration to 3.

change the **num_classes** in this line of code to the number of classes in your dataset.
``` python
  
   train_maskrcnn.modelConfig(network_backbone = "resnet101", num_classes= 3, batch_size = 4)
 
```

**Comment by bappaditya-td** [comment]
I Did that. In config I got this line,  self.IMAGE_META_SIZE = 1 + 3 + 3 + 4 + 1 + self.NUM_CLASSES
In my case NUM_CLASSES = 4, Some images contains different insects, So it is evaluating to 16. Why this input_image_meta is expecting (17,) ? My class label contains space in it, can it be the problem?

**Comment by ayoolaolafenwa** [comment]
> I Did that. In config I got this line, self.IMAGE_META_SIZE = 1 + 3 + 3 + 4 + 1 + self.NUM_CLASSES
> In my case NUM_CLASSES = 4, Some images contains different insects, So it is evaluating to 16. Why this input_image_meta is expecting (17,) ? My class label contains space in it, can it be the problem?

Could you share the modified dataset with me?

**Comment by ayoolaolafenwa** [comment]
@bappaditya-td Have you resolved your problem? I requested the dataset to test it to know what is actually the problem.

**Comment by bappaditya-td** [comment]
Sorry for late reply. I was a bit busy this week. I have sorted out the problem. The test set was not containing same number of classes. That's why during validation it was giving error. Everything is fine now. Only one thing is disturbing me, is the dependency on labelme. You should create a post for reading data with example format separately so that we can customise it as required. Thanks a lot for your concern.

**Comment by Spandyie** [comment]
@ayoolaolafenwa I am getting the same error, is every image in training / validation  required to have all  "n" classes annotated in it ? Say, can a image have n-1 class?
