### ISSUE TITLE
Provide Complete Model & Data Inspection Code/Documentation/Notebook

### ISSUE THREAD

**Issue by khanfarhan10** [ayoolaolafenwa/PixelLib#58]
Would you (@ayoolaolafenwa ) be kind enough to provide a complete inspection code for both the data as well as the model as provided by the official Matterport Implementation? Some samples are provided below:

- inspect_nucleus_data.ipynb 
  - [View on Github](https://github.com/matterport/Mask_RCNN/blob/master/samples/nucleus/inspect_nucleus_data.ipynb)
  - [View in Github1s](https://github1s.com/matterport/Mask_RCNN/blob/master/samples/nucleus/inspect_nucleus_data.ipynb)
- inspect_nucleus_model.ipynb
  - [View on Github](https://github.com/matterport/Mask_RCNN/blob/master/samples/nucleus/inspect_nucleus_model.ipynb)
  - [View in Github1s](https://github1s.com/matterport/Mask_RCNN/blob/master/samples/nucleus/inspect_nucleus_model.ipynb)

Thanks in advance.

**Comment by ayoolaolafenwa** [comment]
@khanfarhan10  Presently I have busy commitments and I may work on it in the nearest future.

**Comment by khanfarhan10** [comment]
Sure @ayoolaolafenwa ! If you'd guide me I could create a notebook!
