### ISSUE TITLE
Unable to locate dataset during Training 

### ISSUE THREAD

**Issue by alic-xc** [ayoolaolafenwa/PixelLib#63]
HI guys,
I'm unable to train my model. 

```
train_maskrcnn.load_pretrained_model("/kaggle/working/mask_rcnn_coco.h5")
train_maskrcnn.load_dataset("fingerling")
train_maskrcnn.train_model(num_epochs = 300, augmentation=True,  path_trained_models = "/kaggle/working")
```
It does not detect or load the dataset. i don't know why it got stuck at Selecting layers to train

```
Using resnet101 as network backbone For Mask R-CNN model
Applying Default Augmentation on Dataset
Train 0 images
Validate 0 images
Checkpoint Path: /kaggle/working
Selecting layers to train
```

**Comment by ayoolaolafenwa** [comment]
@alic-xc Confirm that your dataset folder is not empty. If it is not empty and the problem persists, share the dataset with me.

**Comment by alic-xc** [comment]
> @alic-xc Confirm that your dataset folder is not empty. If it is not empty and the problem persists, share the dataset with me.

I think it is kaggle that was giving me the error. I changed to google colab and it was working fine.
Thanks
