### ISSUE TITLE
How can I get pascal.h5

### ISSUE THREAD

**Issue by babybeibeili** [ayoolaolafenwa/PixelLib#7]
I want to run the demo,but I can't find the file pascal.h5.

**Comment by ayoolaolafenwa** [comment]
@babybeibeili  The deeplab model trained on pascal voc is available as a release in this repository. You can download it directly from here https://github.com/ayoolaolafenwa/PixelLib/releases/download/1.1/deeplabv3_xception_tf_dim_ordering_tf_kernels.h5.
