### ISSUE TITLE
Custom MaskRCNN

### ISSUE THREAD

**Issue by kavi0786** [ayoolaolafenwa/PixelLib#71]
Madam, How to increase the thickness of the bounding box , and label name using pixellib . Thanks in advance...

**Comment by ayoolaolafenwa** [comment]
@kavi0786  I have made it possible to regulate the thickness of the label names and bounding boxes. Upgrade to the latest version of PixelLib using;
```
pip3 install pixellib --upgrade
```
Modified code 
sample image

![sq](https://user-images.githubusercontent.com/52606857/122682963-41bc0a80-d1f4-11eb-8649-49e6d8200c32.jpg)


``` python
import pixellib
from pixellib.instance import custom_segmentation

ins = custom_segmentation()
ins.inferConfig(num_classes=2, class_names=["BG", "butterfly", "squirrel"])
ins.load_model("Nature_model_resnet101.h5")

res, output = ins.segmentImage("sample.jpg", show_bboxes=True, text_size=4, text_thickness=10,
box_thickness= 4,  output_image_name= "output.jpg")
```
**parameters that regulate the thickness of texts and bounding boxes**

*text_size*: The default text size is 0.6 and it is okay with images with low resolutions. It will be small for images with high resolutions. 

*text_thickness*: The default text thickness is 0. I increased it to 4 to match the image resolution.

*box_thickness*: The default box thickness is 2 and I changed it to 10 to match the image resolution.

**Note:** Regulate the parameters according to the resolutions of your images and the values I used for this sample image whose resolution is 3024 x 1998 might be too large if your images' resolutions are lower than this.  You can increase the values of the parameters than the ones I used in this sample code if you have images whose resolutions are very high.

**Note:** *text_thickness* and *box_thickness* parameters' values must always be in integers and do not express their values in floating point numbers. But *text_size* value can be expressed in both integer and floating point numbers. 


**output image without changing the size and thickness of the text and bounding box**
![a2](https://user-images.githubusercontent.com/52606857/122683165-77152800-d1f5-11eb-8037-8b96492543ec.jpg)


**output image with increased text size, text thickness and bounding box thickness.**

![a](https://user-images.githubusercontent.com/52606857/122683184-898f6180-d1f5-11eb-8258-3bcd7cfa6a9b.jpg)

**Comment by kavi0786** [comment]
Madam, in pixellib , any possibility to visualise the results on tensorboard....thanks in advance..

Regards
Kavitha
