### ISSUE TITLE
Multiple images for image segmentation

### ISSUE THREAD

**Issue by archit1508** [ayoolaolafenwa/PixelLib#72]
Hi, 

We are young researchers and find your tool very useful for segmentation. Currently we are in the process of using the image segmentation model for fruit quality evaluation. The model pretrained on COCO works.

How can we save the segmented instances using your library for multiple images and with the same names as our original dataset ? 

Also please note, we will provide proper citations and contribution mentions in any publications. 

Thanks

**Comment by ayoolaolafenwa** [comment]
@archit1508  upgrade to the latest version of PixelLib that supports batch prediction. 
upgrade using;
```
pip3 install pixellib --upgrade
```
Code for batch prediction
``` python
import pixellib
from pixellib.instance import instance_segmentation

ins = instance_segmentation()
ins.load_model("mask_rcnn_coco.h5")
ins.segmentBatch("input_folder",  show_bboxes=True, output_folder_name = "output_folder")
```
