### ISSUE TITLE
Changing IoU Thresholds

### ISSUE THREAD

**Issue by xyntechx** [ayoolaolafenwa/PixelLib#73]
Hi! Thank you for creating PixelLib! I would like to evaluate my model using different IoU thresholds. I have tried to clone the repo and modified the source code but it seems that the IoU threshold used is still 0.5. Can you update the source code such that we can use different thresholds as soon as possible please? Thank you in advance!

**Comment by ayoolaolafenwa** [comment]
@xyntechx It is now possible to change the IOU threshold for model evaluation.  Upgrade to the latest version of PixelLib using;
``` 
pip3 install pixellib --upgrade
```
modified code

``` python
import pixellib
from pixellib.custom_train import instance_custom_training

eval = instance_custom_training()
eval.modelConfig(num_classes=2)

eval.load_dataset("Nature")

#change the iou threshold to the value you want
eval.evaluate_model("Nature_model_resnet101.h5", iou_threshold= 0.4)
```
