### ISSUE TITLE
Why Pixellib is very slow on CPU?

### ISSUE THREAD

**Issue by anjyed** [ayoolaolafenwa/PixelLib#8]
I saw @ayoolaolafenwa's comment on 3 Jun
"Inference time for performing Semantic Segmentation with PixelLib occurs between 7-8 seconds. This is fast enough for obtaining state of the art results with Semantic Segmentation".

But it's not at all 8 seconds.Its taking close to 1 minute in a CPU with 6GB RAM

**Comment by ayoolaolafenwa** [comment]
The inference time is based on running the segmentation model on a GPU, if you want to achieve real time segmentation make use of GPU.
