### ISSUE TITLE
Mean Average Precision 0.000 for "mask_rcnn_coco.h5" for instance_custom_training.

### ISSUE THREAD

**Issue by fsultana44** [ayoolaolafenwa/PixelLib#97]
I am testing PixelLib for the instance segmentation using our custom dataset. At first, I run the model on the CPU only for 18 epochs using batch size 1(we have a very small data set, four training images). The model trained perfectly and detected all the objects in the images, and test performance was 44%. Then I ran the same code and model in the GPU for 250 epochs to get better performance, but it surprised me. I got a Mean Average Precision of 0.0000, and the model could not detect anything. I tried to run several ways by changing batch size, network backbone(resnet101,resnet50), and run the code on the Google colab but have not got any results, always getting  Mean Average Precision 0.0000. I did not get any errors while running the code, and I just got some warnings. How to solve this problem?
Here is some snippet of the warning.
![train_1](https://user-images.githubusercontent.com/51081858/131635457-9e4e8232-ca6c-4fbf-afc5-ea0c09579a45.PNG)
![train_2](https://user-images.githubusercontent.com/51081858/131635462-c202b25a-689e-4c9e-8b22-dc385b7677c2.PNG)
![train_3](https://user-images.githubusercontent.com/51081858/131635463-e52d4097-e60e-4859-87e4-6799e3d522b9.PNG)
![model-eva_pro2](https://user-images.githubusercontent.com/51081858/131635505-46f796b8-10fc-4569-974e-5f35f9f03eb9.PNG)

**Comment by ayoolaolafenwa** [comment]
@fsultana44  PixelLib is having issue with the latest version of tensorflow(2.6.0). Downgrade to any of the tensorflow versions between 2.0-2.50.

**Comment by fsultana44** [comment]
The problem has been solved now, while I tested it again; the previous issue might happen for some other reason.

**Comment by gdeepank** [comment]
Hello @fsultana44 @ayoolaolafenwa. Currently, I am facing the same above issue. I am getting mAP 0.000. I was able to complete the training phase. Could you please let me know how to solve this issue? How were you able to fix the issue?
Your help would be very much appreciated.
